//! Numerical parity tests against `pvlib`.
//!
//! Reads `validation/reference.json` (generated by
//! `validation/generate_reference.py` with pvlib over an Atacama point) and
//! checks every solarpv-core module against the pvlib oracle on the same inputs.
//!
//! Each module is fed pvlib's own upstream values (solar position, dni_extra,
//! airmass) so that errors do not cascade: the solar-position model is judged on
//! its own, the transposition on pvlib geometry, the PV chain on pvlib POA.

use serde_json::Value;
use solarpv_core::{
    irradiance::{erbs, poa_irradiance, relative_airmass, Decomposition, SkyModel},
    pv::{pvwatts_ac, pvwatts_dc, sapm_cell_temperature, TempModel, ETA_INV_NOM, ETA_INV_REF},
    solpos::{solar_position, DateTimeUtc, Location},
};

fn load() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../validation/reference.json");
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("read {path}: {e} — run validation/generate_reference.py"));
    serde_json::from_str(&text).expect("parse reference.json")
}

fn f(v: &Value, k: &str) -> f64 {
    v.get(k).and_then(Value::as_f64).unwrap_or_else(|| panic!("missing {k}"))
}

/// Max absolute and relative error helper. Relative is used when the reference
/// magnitude is non-trivial; small magnitudes fall back to absolute tolerance.
fn assert_close(got: f64, want: f64, abs_tol: f64, rel_tol: f64, what: &str) {
    let err = (got - want).abs();
    let tol = abs_tol.max(rel_tol * want.abs());
    assert!(
        err <= tol,
        "{what}: got {got:.6}, want {want:.6}, |Δ| {err:.6} > tol {tol:.6}"
    );
}

#[test]
fn solar_position_matches_pvlib_spa() {
    let data = load();
    let samples = data["samples"].as_array().unwrap();
    let (mut max_zen, mut max_az) = (0.0_f64, 0.0_f64);
    for s in samples {
        let utc = &s["utc"];
        let when = DateTimeUtc::new(
            utc["year"].as_i64().unwrap() as i32,
            utc["month"].as_u64().unwrap() as u32,
            utc["day"].as_u64().unwrap() as u32,
            utc["hour"].as_u64().unwrap() as u32,
            utc["minute"].as_u64().unwrap() as u32,
            utc["second"].as_u64().unwrap() as u32,
        )
        .unwrap();
        let loc = Location::new(f(s, "lat"), f(s, "lon")).unwrap();
        let p = solar_position(when, loc);

        let want_zen = f(s, "pv_apparent_zenith");
        max_zen = max_zen.max((p.apparent_zenith - want_zen).abs());

        // Azimuth is ill-conditioned when the sun is near the zenith; only
        // compare when it is meaningfully defined.
        if want_zen < 80.0 {
            let mut dz = (p.azimuth - f(s, "pv_azimuth")).abs();
            if dz > 180.0 {
                dz = 360.0 - dz;
            }
            max_az = max_az.max(dz);
        }
    }
    // Michalsky vs NREL SPA: sub-0.1° in zenith, sub-0.3° in azimuth.
    assert!(max_zen < 0.1, "max apparent-zenith error {max_zen:.4}°");
    assert!(max_az < 0.3, "max azimuth error {max_az:.4}°");
}

#[test]
fn erbs_matches_pvlib() {
    let data = load();
    for s in data["samples"].as_array().unwrap() {
        let d = erbs(f(s, "ghi"), f(s, "pv_apparent_zenith"), s["doy"].as_u64().unwrap() as u32);
        assert_close(d.dni, f(s, "erbs_dni"), 0.5, 1e-3, "erbs dni");
        assert_close(d.dhi, f(s, "erbs_dhi"), 0.5, 1e-3, "erbs dhi");
    }
}

#[test]
fn poa_transposition_matches_pvlib() {
    let data = load();
    for s in data["samples"].as_array().unwrap() {
        let decomp = Decomposition { ghi: f(s, "ghi"), dni: f(s, "dni"), dhi: f(s, "dhi") };
        let zen = f(s, "pv_apparent_zenith");
        let az = f(s, "pv_azimuth");
        let tilt = f(s, "tilt");
        let saz = f(s, "surface_azimuth");
        let albedo = f(s, "albedo");
        let dni_extra = f(s, "dni_extra");
        let am = f(s, "airmass");

        for (model, key) in [
            (SkyModel::Isotropic, "isotropic"),
            (SkyModel::HayDavies, "haydavies"),
            (SkyModel::Perez, "perez"),
        ] {
            let poa = poa_irradiance(model, tilt, saz, decomp, zen, az, albedo, dni_extra, am);
            let want = &s["poa"][key];
            assert_close(poa.global, f(want, "global"), 0.5, 2e-3, &format!("poa.global {key}"));
            assert_close(poa.direct, f(want, "direct"), 0.5, 2e-3, &format!("poa.direct {key}"));
            assert_close(
                poa.sky_diffuse,
                f(want, "sky_diffuse"),
                0.5,
                3e-3,
                &format!("poa.sky_diffuse {key}"),
            );
            assert_close(
                poa.ground_diffuse,
                f(want, "ground_diffuse"),
                0.5,
                1e-3,
                &format!("poa.ground {key}"),
            );
        }
    }
}

#[test]
fn pv_chain_matches_pvlib() {
    let data = load();
    for s in data["samples"].as_array().unwrap() {
        let poa_g = f(&s["poa"]["perez"], "global");
        let tcell = sapm_cell_temperature(
            poa_g,
            f(s, "temp_air"),
            f(s, "wind"),
            TempModel::OPEN_RACK_GLASS_GLASS,
        );
        assert_close(tcell, f(s, "tcell"), 1e-3, 1e-4, "tcell");

        let dc = pvwatts_dc(poa_g, tcell, 1000.0, -0.004);
        assert_close(dc, f(s, "dc"), 1e-3, 1e-4, "dc");

        let ac = pvwatts_ac(dc, 1000.0 / 1.1, ETA_INV_NOM, ETA_INV_REF);
        assert_close(ac, f(s, "ac"), 1e-3, 1e-4, "ac");
    }
}

#[test]
fn airmass_matches_pvlib() {
    let data = load();
    for s in data["samples"].as_array().unwrap() {
        let zen = f(s, "pv_apparent_zenith");
        if zen >= 90.0 {
            continue;
        }
        assert_close(relative_airmass(zen), f(s, "airmass"), 1e-3, 1e-4, "airmass");
    }
}
