//! Numerical parity tests against `pvlib`.
//!
//! Reads `validation/reference.json` (generated by
//! `validation/generate_reference.py` with pvlib over an Atacama point) and
//! checks every solarpv-core module against the pvlib oracle on the same inputs.
//!
//! Each module is fed pvlib's own upstream values (solar position, dni_extra,
//! airmass) so that errors do not cascade: the solar-position model is judged on
//! its own, the transposition on pvlib geometry, the PV chain on pvlib POA.

use serde_json::Value;
use solarpv_core::{
    irradiance::{
        erbs, extra_radiation, haurwitz_clearsky_ghi, poa_irradiance, relative_airmass,
        Decomposition, SkyModel,
    },
    pv::{ac_power, pvwatts_ac, pvwatts_dc, sapm_cell_temperature, PvSystem, TempModel, ETA_INV_NOM, ETA_INV_REF},
    losses::{IamModel, PvLosses, SpectralLoss},
    solpos::{solar_position, DateTimeUtc, Location},
    spa::{solar_position_spa, SpaParams},
    tracking::{single_axis, SingleAxisTracker},
};

fn load() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../validation/reference.json");
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("read {path}: {e} — run validation/generate_reference.py"));
    serde_json::from_str(&text).expect("parse reference.json")
}

fn f(v: &Value, k: &str) -> f64 {
    v.get(k).and_then(Value::as_f64).unwrap_or_else(|| panic!("missing {k}"))
}

/// Max absolute and relative error helper. Relative is used when the reference
/// magnitude is non-trivial; small magnitudes fall back to absolute tolerance.
fn assert_close(got: f64, want: f64, abs_tol: f64, rel_tol: f64, what: &str) {
    let err = (got - want).abs();
    let tol = abs_tol.max(rel_tol * want.abs());
    assert!(
        err <= tol,
        "{what}: got {got:.6}, want {want:.6}, |Δ| {err:.6} > tol {tol:.6}"
    );
}

#[test]
fn solar_position_matches_pvlib_spa() {
    let data = load();
    let samples = data["samples"].as_array().unwrap();
    let (mut max_zen, mut max_az) = (0.0_f64, 0.0_f64);
    for s in samples {
        let utc = &s["utc"];
        let when = DateTimeUtc::new(
            utc["year"].as_i64().unwrap() as i32,
            utc["month"].as_u64().unwrap() as u32,
            utc["day"].as_u64().unwrap() as u32,
            utc["hour"].as_u64().unwrap() as u32,
            utc["minute"].as_u64().unwrap() as u32,
            utc["second"].as_u64().unwrap() as u32,
        )
        .unwrap();
        let loc = Location::new(f(s, "lat"), f(s, "lon")).unwrap();
        let p = solar_position(when, loc);

        let want_zen = f(s, "pv_apparent_zenith");
        max_zen = max_zen.max((p.apparent_zenith - want_zen).abs());

        // Azimuth is ill-conditioned when the sun is near the zenith; only
        // compare when it is meaningfully defined.
        if want_zen < 80.0 {
            let mut dz = (p.azimuth - f(s, "pv_azimuth")).abs();
            if dz > 180.0 {
                dz = 360.0 - dz;
            }
            max_az = max_az.max(dz);
        }
    }
    // Michalsky vs NREL SPA: sub-0.1° in zenith, sub-0.3° in azimuth.
    assert!(max_zen < 0.1, "max apparent-zenith error {max_zen:.4}°");
    assert!(max_az < 0.3, "max azimuth error {max_az:.4}°");
}

#[test]
fn erbs_matches_pvlib() {
    let data = load();
    for s in data["samples"].as_array().unwrap() {
        let d = erbs(f(s, "ghi"), f(s, "pv_apparent_zenith"), s["doy"].as_u64().unwrap() as u32);
        assert_close(d.dni, f(s, "erbs_dni"), 0.5, 1e-3, "erbs dni");
        assert_close(d.dhi, f(s, "erbs_dhi"), 0.5, 1e-3, "erbs dhi");
    }
}

#[test]
fn poa_transposition_matches_pvlib() {
    let data = load();
    for s in data["samples"].as_array().unwrap() {
        let decomp = Decomposition { ghi: f(s, "ghi"), dni: f(s, "dni"), dhi: f(s, "dhi") };
        let zen = f(s, "pv_apparent_zenith");
        let az = f(s, "pv_azimuth");
        let tilt = f(s, "tilt");
        let saz = f(s, "surface_azimuth");
        let albedo = f(s, "albedo");
        let dni_extra = f(s, "dni_extra");
        let am = f(s, "airmass");

        for (model, key) in [
            (SkyModel::Isotropic, "isotropic"),
            (SkyModel::HayDavies, "haydavies"),
            (SkyModel::Perez, "perez"),
        ] {
            let poa = poa_irradiance(model, tilt, saz, decomp, zen, az, albedo, dni_extra, am);
            let want = &s["poa"][key];
            assert_close(poa.global, f(want, "global"), 0.5, 2e-3, &format!("poa.global {key}"));
            assert_close(poa.direct, f(want, "direct"), 0.5, 2e-3, &format!("poa.direct {key}"));
            assert_close(
                poa.sky_diffuse,
                f(want, "sky_diffuse"),
                0.5,
                3e-3,
                &format!("poa.sky_diffuse {key}"),
            );
            assert_close(
                poa.ground_diffuse,
                f(want, "ground_diffuse"),
                0.5,
                1e-3,
                &format!("poa.ground {key}"),
            );
        }
    }
}

#[test]
fn pv_chain_matches_pvlib() {
    let data = load();
    for s in data["samples"].as_array().unwrap() {
        let poa_g = f(&s["poa"]["perez"], "global");
        let tcell = sapm_cell_temperature(
            poa_g,
            f(s, "temp_air"),
            f(s, "wind"),
            TempModel::OPEN_RACK_GLASS_GLASS,
        );
        assert_close(tcell, f(s, "tcell"), 1e-3, 1e-4, "tcell");

        let dc = pvwatts_dc(poa_g, tcell, 1000.0, -0.004);
        assert_close(dc, f(s, "dc"), 1e-3, 1e-4, "dc");

        let ac = pvwatts_ac(dc, 1000.0 / 1.1, ETA_INV_NOM, ETA_INV_REF);
        assert_close(ac, f(s, "ac"), 1e-3, 1e-4, "ac");
    }
}

#[test]
fn nrel_spa_matches_pvlib_sub_arcminute() {
    let data = load();
    let params = SpaParams::default(); // delta_t 67, 101325 Pa, 12 °C, 0.5667°
    let (mut max_zen, mut max_az) = (0.0_f64, 0.0_f64);
    for c in data["spa"].as_array().unwrap() {
        let utc = &c["utc"];
        let when = DateTimeUtc::new(
            utc["year"].as_i64().unwrap() as i32,
            utc["month"].as_u64().unwrap() as u32,
            utc["day"].as_u64().unwrap() as u32,
            utc["hour"].as_u64().unwrap() as u32,
            utc["minute"].as_u64().unwrap() as u32,
            utc["second"].as_u64().unwrap() as u32,
        )
        .unwrap();
        let loc = Location::new(f(c, "lat"), f(c, "lon")).unwrap();
        let p = SpaParams { elevation: f(c, "altitude"), ..params };
        let s = solar_position_spa(when, loc, &p);

        max_zen = max_zen.max((s.apparent_zenith - f(c, "apparent_zenith")).abs());
        let mut dz = (s.azimuth - f(c, "azimuth")).abs();
        if dz > 180.0 {
            dz = 360.0 - dz;
        }
        max_az = max_az.max(dz);
    }
    // NREL SPA reproduces pvlib to a few arcseconds — far below an arcminute.
    assert!(max_zen < 0.0005, "max zenith error {max_zen:.6}° (~{:.1} arcsec)", max_zen * 3600.0);
    assert!(max_az < 0.002, "max azimuth error {max_az:.6}° (~{:.1} arcsec)", max_az * 3600.0);
}

#[test]
fn iam_models_match_pvlib() {
    let data = load();
    let l = &data["losses"];
    let aois: Vec<f64> = l["aois"].as_array().unwrap().iter().map(|v| v.as_f64().unwrap()).collect();
    let models: [(&str, IamModel); 3] = [
        ("ashrae", IamModel::ashrae()),
        ("martin_ruiz", IamModel::martin_ruiz()),
        ("physical", IamModel::physical()),
    ];
    for (key, model) in models {
        let want: Vec<f64> =
            l["iam"][key].as_array().unwrap().iter().map(|v| v.as_f64().unwrap()).collect();
        for (i, &aoi) in aois.iter().enumerate() {
            assert_close(model.iam(aoi), want[i], 1e-6, 1e-6, &format!("iam {key} @ {aoi}°"));
        }
    }
}

#[test]
fn pvwatts_loss_breakdown_matches_pvlib() {
    let data = load();
    let want = f(&data["losses"], "pvwatts_losses_pct");
    assert_close(PvLosses::default().total_percent(), want, 1e-6, 1e-6, "pvwatts losses %");
}

#[test]
fn spectral_factor_matches_pvlib() {
    let data = load();
    let sp = &data["spectral"];
    let coeffs = &sp["coefficients"];
    let model = SpectralLoss::new(
        f(coeffs, "A0"), f(coeffs, "A1"), f(coeffs, "A2"), f(coeffs, "A3"), f(coeffs, "A4"),
    );
    let ams: Vec<f64> = sp["airmass_absolute"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap())
        .collect();
    let want: Vec<f64> = sp["factors"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap())
        .collect();
    for (i, &am) in ams.iter().enumerate() {
        assert_close(model.factor(am), want[i], 1e-6, 1e-6, &format!("spectral factor @ AM={am}"));
    }
}

#[test]
fn haurwitz_matches_pvlib() {
    let data = load();
    for s in data["samples"].as_array().unwrap() {
        let got = haurwitz_clearsky_ghi(f(s, "pv_apparent_zenith"));
        assert_close(got, f(s, "haurwitz_ghi"), 0.5, 1e-3, "haurwitz ghi");
    }
}

/// End-to-end: reproduce pvlib's full-year hourly clear-sky → fixed-tilt POA →
/// PVWatts integration at the Atacama point and match the annual totals. This
/// exercises the entire model chain composed together, not just the parts.
#[test]
fn annual_point_chain_matches_pvlib() {
    let data = load();
    let ap = &data["annual_point"];
    let year = ap["year"].as_i64().unwrap() as i32;
    let tilt = f(ap, "tilt");
    let surf_az = f(ap, "surface_azimuth");
    let albedo = f(ap, "albedo");
    let temp_air = f(ap, "temp_air");
    let wind = f(ap, "wind");
    let loc = Location::new(-23.0, -69.0).unwrap();
    let system = PvSystem::reference_1kw(); // pdc0 1000, γ -0.004, DC/AC 1.1, 14% loss, open-rack

    let mut poa_year = 0.0;
    let mut ac_year = 0.0;
    for doy in 1..=365u32 {
        let day = DateTimeUtc::from_ordinal(year, doy).unwrap();
        for hour in 0..24u32 {
            let when = DateTimeUtc::new(year, day.month, day.day, hour, 0, 0).unwrap();
            let sun = solar_position(when, loc);
            if sun.apparent_elevation <= 0.0 {
                continue;
            }
            let z = sun.apparent_zenith;
            let ghi = haurwitz_clearsky_ghi(z);
            let decomp = erbs(ghi, z, doy);
            let poa = poa_irradiance(
                SkyModel::Perez, tilt, surf_az, decomp, z, sun.azimuth, albedo,
                extra_radiation(doy), relative_airmass(z),
            );
            poa_year += poa.global; // dt = 1 h → Wh/m²
            ac_year += ac_power(&system, poa.global, temp_air, wind);
        }
    }

    // Only residual difference vs pvlib is Michalsky vs NREL SPA solar position.
    assert_close(poa_year, f(ap, "annual_poa_wh"), 0.0, 0.005, "annual POA Wh/m²");
    assert_close(ac_year, f(ap, "annual_ac_wh"), 0.0, 0.005, "annual AC Wh");
}

#[test]
fn single_axis_tracking_matches_pvlib() {
    let data = load();
    for c in data["tracking"].as_array().unwrap() {
        let tracker = SingleAxisTracker {
            axis_tilt: f(c, "axis_tilt"),
            axis_azimuth: f(c, "axis_azimuth"),
            max_angle: f(c, "max_angle"),
            backtrack: c["backtrack"].as_bool().unwrap(),
            gcr: f(c, "gcr"),
            cross_axis_tilt: 0.0,
        };
        let o = single_axis(&tracker, f(c, "zenith"), f(c, "azimuth")).expect("sun up");
        let what = format!("tracker(at={}, aa={}, bt={})", tracker.axis_tilt, tracker.axis_azimuth, tracker.backtrack);
        assert_close(o.tracker_theta, f(c, "tracker_theta"), 1e-4, 1e-5, &format!("{what} theta"));
        assert_close(o.surface_tilt, f(c, "surface_tilt"), 1e-4, 1e-5, &format!("{what} tilt"));
        assert_close(o.surface_azimuth, f(c, "surface_azimuth"), 1e-4, 1e-5, &format!("{what} az"));
        assert_close(o.aoi, f(c, "aoi"), 1e-4, 1e-5, &format!("{what} aoi"));
    }
}

#[test]
fn airmass_matches_pvlib() {
    let data = load();
    for s in data["samples"].as_array().unwrap() {
        let zen = f(s, "pv_apparent_zenith");
        if zen >= 90.0 {
            continue;
        }
        assert_close(relative_airmass(zen), f(s, "airmass"), 1e-3, 1e-4, "airmass");
    }
}
